export const SIGNUP = "SIGNUP";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GET_APARTMENTS = "GET_APARTMENTS";
export const ADD_APARTMENT = "ADD_APARTMENT";
export const UPDATE_APARTMENT = "UPDATE_APARTMENT";
export const DELETE_APARTMENT = "DELETE_APARTMENT";
export const SET_APARTMENTS_FILTER = "SET_APARTMENTS_FILTER";
